# ===============================
# =       SERVER CONFIG        =
# ===============================
server:
  port: 8081
  servlet:
    context-path: /api
  error:
    whitelabel:
      enabled: false
    include-message: always
    include-binding-errors: always

# ===============================
# =       SPRING CONFIG        =
# ===============================
spring:
  application:
    name: my-spring-boot-app
  profiles:
    active: dev
  main:
    banner-mode: "console"
    allow-bean-definition-overriding: true

  # Login Credentials
  security:
    user:
      name: anil
      password: mysecret123
      roles: ADMIN

# ===============================
# =       ACTUATOR CONFIG      =
# ===============================
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: "always"
  server:
    port: 8081

# ===============================
# =       INFO CONFIG          =
# ===============================
info:
  app:
    name: My Spring Boot App
    version: 1.0.0
    maintainer: Anil Kumar

# ===============================
# =       LOGGING CONFIG       =
# ===============================
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.example: DEBUG
  file:
    name: logs/app.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# ===============================
# =       SWAGGER CONFIG       =
# ===============================
  springdoc:
   api-docs:
     path: /v3/api-docs
   swagger-ui:
     path: /swagger-ui.html
     enabled: true


# ===============================
# =       CUSTOM PROPERTIES    =
# ===============================
custom:
  app:
    version: 1.0.0
    maintainer: Anil Kumar


